apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6ccec4df-02da-467f-bb98-c70302c3ea7c"
    keyvaultName: "acrdevsecopslabkeyvault"
    tenantId: "dc522326-6ac7-4382-be7c-bf7cc2c36723"
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
  secretObjects:
    - secretName: app-secret-from-kv
      type: Opaque
      data:
        - objectName: database-url
          key: DATABASE_URL