apiVersion: v1
kind: ServiceAccount
metadata:
  name: sampleapp-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "6ccec4df-02da-467f-bb98-c70302c3ea7c"
  labels:
    azure.workload.identity/use: "true"