#!/bin/bash
# scripts/collect-compliance-evidence.sh

REPORT_DIR="compliance/evidence"
DATE=$(date +%Y%m%d)
REPORT_FILE="$REPORT_DIR/report-$DATE.md"

mkdir -p $REPORT_DIR

cat << 'EOF' > $REPORT_FILE
# 🛡️ Compliance Evidence Report
EOF

echo "**Generated:** $(date)" >> $REPORT_FILE
echo "" >> $REPORT_FILE

# Defender Score
echo "## 📊 Defender for Cloud Secure Score" >> $REPORT_FILE
echo "" >> $REPORT_FILE
echo "| Control | Score | Max | Status |" >> $REPORT_FILE
echo "|---------|-------|-----|--------|" >> $REPORT_FILE

az security secure-score-controls list --query "[].{Control:displayName, Score:current, Max:max}" -o json 2>/dev/null | \
jq -r '.[] | "| \(.Control) | \(.Score) | \(.Max) | \(if .Score == .Max then "✅" elif .Score == 0 then "❌" else "⚠️" end) |"' >> $REPORT_FILE

echo "" >> $REPORT_FILE

# Calculate total
TOTAL=$(az security secure-score-controls list --query "[].{Score:current, Max:max}" -o json 2>/dev/null | jq '[.[].Score] | add')
MAX=$(az security secure-score-controls list --query "[].{Score:current, Max:max}" -o json 2>/dev/null | jq '[.[].Max] | add')
PCT=$((TOTAL * 100 / MAX))

echo "**Overall Score: $TOTAL / $MAX ($PCT%)**" >> $REPORT_FILE
echo "" >> $REPORT_FILE

# Kyverno Summary
echo "## 🔒 Kyverno Policy Compliance" >> $REPORT_FILE
echo "" >> $REPORT_FILE
echo "| Namespace | Resource | Pass | Fail | Status |" >> $REPORT_FILE
echo "|-----------|----------|------|------|--------|" >> $REPORT_FILE

kubectl get policyreport -A -o json 2>/dev/null | jq -r '
.items[] | 
"| \(.metadata.namespace) | \(.scope.kind)/\(.scope.name) | \(.summary.pass) | \(.summary.fail) | \(if .summary.fail == 0 then "✅" else "❌" end) |"
' >> $REPORT_FILE

echo "" >> $REPORT_FILE

# Kyverno totals
PASS_TOTAL=$(kubectl get policyreport -A -o json 2>/dev/null | jq '[.items[].summary.pass] | add')
FAIL_TOTAL=$(kubectl get policyreport -A -o json 2>/dev/null | jq '[.items[].summary.fail] | add')

echo "**Total: $PASS_TOTAL passed, $FAIL_TOTAL failed**" >> $REPORT_FILE
echo "" >> $REPORT_FILE

# Failures breakdown
echo "## ❌ Policy Failures (excluding kube-system)" >> $REPORT_FILE
echo "" >> $REPORT_FILE

FAILURES=$(kubectl get policyreport -A -o json 2>/dev/null | jq -r '
.items[] | 
select(.metadata.namespace != "kube-system") |
select(.summary.fail > 0) |
.results[] | 
select(.result == "fail") |
"- **\(.policy)**: \(.message | split(" ") | .[0:15] | join(" "))..."
')

if [ -z "$FAILURES" ]; then
    echo "✅ No policy failures in application namespaces!" >> $REPORT_FILE
else
    echo "$FAILURES" >> $REPORT_FILE
fi

echo "" >> $REPORT_FILE

# Gatekeeper constraints
echo "## 🚧 Gatekeeper Constraints" >> $REPORT_FILE
echo "" >> $REPORT_FILE
echo "| Constraint | Enforcement | Violations |" >> $REPORT_FILE
echo "|------------|-------------|------------|" >> $REPORT_FILE

kubectl get constraints -A -o json 2>/dev/null | jq -r '
.items[] | 
"| \(.metadata.name) | \(.spec.enforcementAction // "deny") | \(.status.totalViolations // 0) |"
' >> $REPORT_FILE 2>/dev/null || echo "No Gatekeeper constraints found" >> $REPORT_FILE

echo "" >> $REPORT_FILE
echo "---" >> $REPORT_FILE
echo "*Report generated by collect-compliance-evidence.sh*" >> $REPORT_FILE

echo "✅ Report saved to $REPORT_FILE"

# Also output to terminal
cat $REPORT_FILE